version: '3.4'

services:
  gametimeradmin:
    image: gametimeradmin
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresdb
      
    environment:
      DATABASE_URL: postgres://Root:nu09q7n7RZumlKsCJW8Om8ujXm5s6XSd@postgres:5432/gametimer_development
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      ACCESSTOKENSECRET: 88585HHWUUSUSD6Q66562345g5098766
    ports:
      - 3000:3000
    links:
      - postgresdb
    volumes:
      - './:/src'

  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: Root
      POSTGRES_PASSWORD: nu09q7n7RZumlKsCJW8Om8ujXm5s6XSd
      POSTGRES_DB: gametimer_development
